
[cursor]
style = "Underline"

[env]
TERM = "alacritty"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

# [font.bold_italic]
# family = "FiraCode Nerd Font Mono"
# style = "Bold Italic"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[general]
import = ["/home/majortom/.config/alacritty/colors/jellybeans.toml"]
